spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_expense_db
    username: postgres
    password: root
  jpa:
    show-sql : true
    hibernate:
     ddl-auto: update

  profiles:
    active: dev
